// End-to-end check of the runner protocol against a running server.
import { createRequire } from "node:module";
import { createHash, randomBytes } from "node:crypto";
const require = createRequire(import.meta.url);
const { PrismaClient } = require("../src/generated/prisma");

const BASE = process.env.BASE || "http://127.0.0.1:3210";
const db = new PrismaClient();
const ok = [];
const bad = [];
const check = (name, cond, extra = "") => (cond ? ok : bad).push(`${cond ? "PASS" : "FAIL"} ${name}${extra ? ` — ${extra}` : ""}`);

const token = `gnt_rnr_${randomBytes(24).toString("base64url")}`;
const hash = createHash("sha256").update(token).digest("hex");
const H = { "content-type": "application/json", authorization: `Bearer ${token}` };

const user = await db.user.create({ data: { email: `smoke-${Date.now()}@example.test`, name: "Smoke Test" } });
const ws = await db.workspace.create({
  data: { name: "Smoke", slug: `smoke-${Date.now()}`, members: { create: { userId: user.id, role: "owner" } } },
});
const sprint = await db.sprint.create({
  data: { workspaceId: ws.id, name: "Smoke sprint", startsAt: new Date(), endsAt: new Date(Date.now() + 864e5), capacityPoints: 10 },
});
const story = await db.story.create({
  data: { sprintId: sprint.id, key: "SMK-1", title: "Runner claims and completes a job", acceptanceCriteria: JSON.stringify(["it works"]) },
});
const run = await db.run.create({ data: { workspaceId: ws.id, sprintId: sprint.id, agent: "qe-batch", mode: "batch", status: "running" } });
const job = await db.job.create({
  data: { runId: run.id, storyId: story.id, kind: "spec-gen", status: "queued", payloadJson: JSON.stringify({ storyKey: "SMK-1" }) },
});
const runner = await db.runner.create({
  data: { workspaceId: ws.id, name: "smoke-runner", kind: "local", slots: 2, tokenHash: hash, tokenHint: token.slice(-6) },
});

// 1. an unauthenticated claim must be rejected
let r = await fetch(`${BASE}/api/runner/claim`, { method: "POST", headers: { "content-type": "application/json" } });
check("unauthenticated claim rejected", r.status === 401, `got ${r.status}`);

// 2. a bad token must be rejected
r = await fetch(`${BASE}/api/runner/claim`, { method: "POST", headers: { ...H, authorization: "Bearer gnt_rnr_wrong" } });
check("bad token rejected", r.status === 401, `got ${r.status}`);

// 3. heartbeat
r = await fetch(`${BASE}/api/runner/heartbeat`, { method: "POST", headers: H, body: JSON.stringify({ version: "1.0.0", slots: 2, activeJobs: 0 }) });
let body = await r.json();
check("heartbeat accepted", r.ok && body.ok === true, JSON.stringify(body).slice(0, 120));
check("heartbeat returns runner identity", body.runner?.name === "smoke-runner");

// 4. claim the queued job
r = await fetch(`${BASE}/api/runner/claim`, { method: "POST", headers: H, body: "{}" });
body = await r.json();
check("job claimed", body.job?.id === job.id, JSON.stringify(body).slice(0, 160));
check("claim carries the story payload", body.job?.storyKey === "SMK-1");

// 5. a second claim must not hand back the same job
r = await fetch(`${BASE}/api/runner/claim`, { method: "POST", headers: H, body: "{}" });
body = await r.json();
check("no double-claim", body.job === null || body.job === undefined, JSON.stringify(body).slice(0, 120));

// 6. stream logs
r = await fetch(`${BASE}/api/runner/jobs/${job.id}/log`, {
  method: "POST", headers: H,
  body: JSON.stringify({ lines: [{ message: "npx playwright test", level: "info" }, { message: "3 passed", level: "ok" }] }),
});
body = await r.json();
check("log lines accepted", r.ok && body.written === 2, JSON.stringify(body).slice(0, 120));

// 7. complete with an asset
r = await fetch(`${BASE}/api/runner/jobs/${job.id}/complete`, {
  method: "POST", headers: H,
  body: JSON.stringify({ status: "passed", assets: [{ path: "tests/smk-1.spec.ts", kind: "spec", content: "// generated by smoke test\n" }] }),
});
body = await r.json();
check("job completed", r.ok && body.status === "passed", JSON.stringify(body).slice(0, 120));

// 8. verify the database reflects all of it
const finalJob = await db.job.findUnique({ where: { id: job.id }, include: { assets: true } });
const finalRun = await db.run.findUnique({ where: { id: run.id }, include: { events: true } });
const finalStory = await db.story.findUnique({ where: { id: story.id } });
const finalRunner = await db.runner.findUnique({ where: { id: runner.id } });
check("job marked passed", finalJob.status === "passed", finalJob.status);
check("asset stored", finalJob.assets.length === 1 && finalJob.assets[0].path === "tests/smk-1.spec.ts");
check("run auto-closed as succeeded", finalRun.status === "succeeded", finalRun.status);
check("events recorded", finalRun.events.length >= 4, `${finalRun.events.length} events`);
check("story marked green", finalStory.status === "green", finalStory.status);
check("runner slot released", finalRunner.activeJobs === 0, `activeJobs=${finalRunner.activeJobs}`);

// 9. cross-workspace isolation: another workspace's runner must not see this job
const otherWs = await db.workspace.create({ data: { name: "Other", slug: `other-${Date.now()}` } });
const otherToken = `gnt_rnr_${randomBytes(24).toString("base64url")}`;
await db.runner.create({
  data: { workspaceId: otherWs.id, name: "other-runner", tokenHash: createHash("sha256").update(otherToken).digest("hex"), tokenHint: "x" },
});
const job2 = await db.job.create({ data: { runId: run.id, kind: "spec-gen", status: "queued", payloadJson: "{}" } });
r = await fetch(`${BASE}/api/runner/claim`, {
  method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${otherToken}` }, body: "{}",
});
body = await r.json();
check("runner cannot claim another workspace's job", !body.job, JSON.stringify(body).slice(0, 120));

// cleanup
await db.job.deleteMany({ where: { runId: run.id } });
await db.workspace.deleteMany({ where: { id: { in: [ws.id, otherWs.id] } } });
await db.user.delete({ where: { id: user.id } });
await db.$disconnect();

console.log([...ok, ...bad].join("\n"));
console.log(`\n${ok.length} passed, ${bad.length} failed`);
process.exit(bad.length ? 1 : 0);
